//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Calificación_de_Estudiantes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int CalificacionID { get; set; }
        public int EstudianteID { get; set; }
        public int MateriaID { get; set; }
        public int Periodo1 { get; set; }
        public int Periodo2 { get; set; }
        public int Periodo3 { get; set; }
        public int Periodo4 { get; set; }
        public int Examen { get; set; }
        public Nullable<decimal> TotalCalificacion { get; set; }
        public string Clasificacion { get; set; }
        public string Estado { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Materia Materia { get; set; }

        public DateTime? FechaRegistro { get; set; }
    }
}
